name: LAPRAS Card

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  update-card:
    name: LAPRAS Card
    runs-on: ubuntu-latest
    steps:
      - uses: kawamataryo/lapras-card-readme@main
        with:
          CARD_WIDTH: "400"
          UPDATE_TIME: "true"
          SHARE_ID: "MIBGQP7"
          ICON_FIRST: "#212121"
          ICON_SECOND: "#000000"
          BACKGROUND_FIRST: "#000000"
          BACKGROUND_SECOND: "#212121"
          LANG: "ja"
